In [1]:
import tensorflow as tf

In [3]:
a = 3
# tensorflow 底层的基本结构 tensor形式
# 创建一个变量,同时如同numpy一样，tf也有自己的数据类型
w = tf.Variable([[0.5, 1.0]])
x = tf.Variable([[2.0], [1.0]])


# 然后定义一个“操作”
y = tf.matmul(w, x)

In [4]:
# 现在只是被定义好，但是没有进行实例化
# 进行实例化操作
init_op = tf.global_variables_initializer()

In [5]:
# 构造一个计算域
with tf.Session() as sess:
    sess.run(init_op)
    print(y.eval())

[[ 2.]]


In [6]:
y

<tf.Tensor 'MatMul:0' shape=(1, 1) dtype=float32>

In [7]:
x

<tf.Variable 'Variable_3:0' shape=(2, 1) dtype=float32_ref>

In [19]:
a = tf.zeros([3, 4], dtype=tf.int32)
b = tf.ones([2, 3], dtype=tf.int32)

## 在TensorFlow中推荐使用的数据类型为：float32 在cpu和gpu模式下都可以使用

In [20]:
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])
c = tf.ones_like(tensor)

In [24]:
init_op1 = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init_op1)
    print("a:")
    print(a.eval())
    print("b:")
    print(b.eval())
    print("c:")
    print(c.eval())

a:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
b:
[[1 1 1]
 [1 1 1]]
c:
[[1 1 1]
 [1 1 1]]


In [25]:
# Constant 2-D tensor populated with scalar value -1
tensor = tf.constant(-1.0, shape=[2, 3])
init_op = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init_op)
    print(tensor.eval())

[[-1. -1. -1.]
 [-1. -1. -1.]]


In [30]:
linspace = tf.linspace(10.0, 12.0, 3, name="linspace")
init_op = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init_op)
    print(linspace.eval())

[ 10.  11.  12.]


## 对Variable中的name的解释    
    意识到TensorFlow不仅仅有Python API，
    还有C++, Go, Java等API也可以构建计算图（computation graph）,即我们
    所说的“模型”。构建好的模型，我们可以将其保存成 “checkpoints”或者“SaveModel”
    在其他语言环境中被调用。
    最常见的就是在Python里面作模型的构建和训练，
    存储后在tensorflow-serving库的C++环境中打开进行部署
    
    Python的变量名只有Python知道。但是你用name关键字定义的节点和张量名称，
    是模型本身的一部分，会和你的模型一起存储到checkpoint或SavedModel里面去。
    
    你要是不去自己指定name关键字的值的话, TensorFlow的Python API会自己给一个默认名字，
    一般是运算（operation）本身的名字，加一个_n后缀避免重复。但是如果明确命名，
    对日后调试等可能会有帮助。

In [35]:
start = 3
limit = 18
delta = 3
range_1 = tf.range(start, limit, delta)
init_op = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init_op)
    print(range_1.eval())

[ 3  6  9 12 15]


In [37]:
# 常量初始化
c = tf.constant([[1,2],[3,4],[5,6]])

In [38]:
# 随机初始化，符合高斯分布
norm = tf.random_normal([2,3], mean=-1, stddev=4)

In [39]:
# 将c中元素的顺序打乱
shuff = tf.random_shuffle(c)

In [40]:
sess = tf.Session()
print(sess.run(norm))
print(sess.run(shuff))

[[-1.3577776  -4.83104324  1.82828331]
 [-4.23801947  3.10177279 -7.79831362]]
[[5 6]
 [3 4]
 [1 2]]


In [44]:
state = tf.Variable(0)  # state 是一个tf变量
new_value = tf.add(state, tf.constant(1))
update = tf.assign(state, new_value)
# 这个assign操作的作用是把 new_value的值赋给state

# 以上把这一系列操作的骨架定义完了
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())   #这个是run一个全局变量的初始化
    print(sess.run(state))  
    for _ in range(3):
        sess.run(update)  # 需要run这个操作
        print(sess.run(state))

0
1
2
3


In [45]:
d = tf.zeros([3, 4], dtype=tf.int32)

In [46]:
d

<tf.Tensor 'zeros_2:0' shape=(3, 4) dtype=int32>

In [48]:
with tf.Session() as sess:
    print(sess.run(d))
    print(d.eval())

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [51]:
# numpy与 TensorFlow之间的相互转换
import numpy as np
a = np.zeros((3,3))
print(type(a))
ta = tf.convert_to_tensor(a)
with tf.Session() as sess:
    print(sess.run(ta))

<class 'numpy.ndarray'>
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [54]:
# 这个功能经常用在 batch梯度下降里面
input1 = tf.placeholder(tf.float32)
input2 = tf.placeholder(tf.float32) # 指定好input1和input2的类型就好
output = tf.multiply(input1, input2)
with tf.Session() as sess:
    print(sess.run([output], feed_dict={input1:[7.,2.], input2:[2.,1.]}))

[array([ 14.,   2.], dtype=float32)]


## tf.train.Saver
将当前的状态进行一个保存操作，以便在今后的实验中进行调用

In [ ]:
w = tf.Variable([[0.5,1.0]])
x = tf.Variable([[2.0],[1.0]])
y = tf.matmul(w,x)
init_op = tf.global_variables_initializer()
saver = tf.train.Saver()

with tf.Session() as sess:
    sess..run(init_op)
    # 执行一些模型操作，并将变量保存在磁盘上
    save_path = saver.save(sess, "/User/lxp/....")